name: nuclear_forces_app
description: App for managing deliveries, collecting and repair orders from the 12 electrons webapp.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^2.27.1
  # Firestore database
  cloud_firestore: ^4.15.9
  # Firebase authentication
  firebase_auth: ^4.19.5

  # UI extras
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
